class_name Quotes

const quotes = [
	["Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"],
	["We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.", "Carl Sagan"],
	["Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality. Searching and learning is where the miracle process all begins.", "Jim Rohn"],
	["We are all born ignorant, but one must work hard to remain stupid.", "Benjamin Franklin"],
	["A liberally educated person meets new ideas with curiosity and fascination. An illiberally educated person meets new ideas with fear.", "James Stockdale"],
	["It must be remembered that the purpose of education is not to fill the minds of students with facts... it is to teach them to think.", "Robert M. Hutchins"],
	["Why should society feel responsible only for the education of children, and not for the education of all adults of every age?", "Erich Fromm"],
	["The function of education is to teach one to think intensively and to think critically. Intelligence plus character - that is the goal of true education.", "Martin Luther King, Jr."],
	["The principle goal of education in the schools should be creating men and women who are capable of doing new things, not simply repeating what other generations have done.", "Jean Piaget"],
	["The beautiful thing about learning is nobody can take it away from you.", "B. B. King"],
	["It is impossible for a man to learn what he thinks he already knows.", "Epictetus"],
	["Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", "Malcolm X"],
	["The great aim of education is not knowledge but action.", "Herbert Spencer"],
	["No matter how many mistakes you make or how slow you progress, you are still way ahead of everyone who isn't trying.", "Tony Robbins"],
	["A man who wants to lead the orchestra must turn his back on the crowd.", "Max Lucado"],
	["Trust in yourself. Your perceptions are often far more accurate than you are willing to believe.", "Claudia Black"],
	["Love, creativity, and opportunity is in the air. Take it in and do your thing.", "Lenny Kravitz"],
	["Learn from the negative as well as the positive, from the failures as well as the successes.", "Jim Rohn"],
	["Some men have thousands of reasons why they cannot do what they want to, when all they need is one reason why they can.", "Martha Graham"],
	["If you run into a wall, don't turn around and give up. Figure out how to climb it.", "Michael Jordan"],
	["Genius is one percent inspiration, ninety-nine percent perspiration.", "Thomas A. Edison"],
	["One doesn't discover new lands without consenting to lose sight, for a very long time, of the shore.", "Andre Gide"],
	["Explore. Dream. Discover.", "Mark Twain"],
	["We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.", "T. S. Eliot"],
	["Success is an act of exploration. That means the first thing you have to find is the unknown. Learning is searching; anything else is just waiting.", "Dale Dauten"],
	["In any field, find the strangest thing and then explore it.", "John Archibald Wheeler"],
	["The greatest discoveries all start with the question 'Why?'", "Robert Ballard"],
	["I do not explain, I explore.", "Marshall McLuhan"],
	["Exploration is really the essence of the human spirit.", "Frank Borman"],
]

static func random() -> Array: return quotes.pick_random()
