class_name NameGenerator

var russian_names := WordGenerator.new(WordGenerator.SourcePath.none)
var satellites := WordGenerator.new(WordGenerator.SourcePath.none)
var scottish_names := WordGenerator.new(WordGenerator.SourcePath.none)
var spanish_names := WordGenerator.new(WordGenerator.SourcePath.none)
var swedish_names := WordGenerator.new(WordGenerator.SourcePath.none)
var swiss_names := WordGenerator.new(WordGenerator.SourcePath.none)
var capital_cities := WordGenerator.new(WordGenerator.SourcePath.none)
var chinese_names := WordGenerator.new(WordGenerator.SourcePath.none)
var constellations := WordGenerator.new(WordGenerator.SourcePath.none)
var cumbria_names := WordGenerator.new(WordGenerator.SourcePath.none)
var dutch_names := WordGenerator.new(WordGenerator.SourcePath.none)
var english_names := WordGenerator.new(WordGenerator.SourcePath.none)
var french_names := WordGenerator.new(WordGenerator.SourcePath.none)
var german_names := WordGenerator.new(WordGenerator.SourcePath.none)
var greek_islands := WordGenerator.new(WordGenerator.SourcePath.none)
var iclandic_names := WordGenerator.new(WordGenerator.SourcePath.none)
var indian_names := WordGenerator.new(WordGenerator.SourcePath.none)
var irish_names := WordGenerator.new(WordGenerator.SourcePath.none)
var italian_names := WordGenerator.new(WordGenerator.SourcePath.none)
var japanese_names := WordGenerator.new(WordGenerator.SourcePath.none)
var roman_names := WordGenerator.new(WordGenerator.SourcePath.none)
var latin_names := WordGenerator.new(WordGenerator.SourcePath.none)

func save(world_name: String) -> void:
	var file := FileAccess.open("user://worlds/%s/names.json" % (world_name), FileAccess.WRITE)
	var data := {}
	data["russian_names"] = russian_names.save_dict()
	data["satellites"] = satellites.save_dict()
	data["scottish_names"] = scottish_names.save_dict()
	data["spanish_names"] = spanish_names.save_dict()
	data["swedish_names"] = swedish_names.save_dict()
	data["swiss_names"] = swiss_names.save_dict()
	data["capital_cities"] = capital_cities.save_dict()
	data["chinese_names"] = chinese_names.save_dict()
	data["constellations"] = constellations.save_dict()
	data["cumbria_names"] = cumbria_names.save_dict()
	data["dutch_names"] = dutch_names.save_dict()
	data["english_names"] = english_names.save_dict()
	data["french_names"] = french_names.save_dict()
	data["german_names"] = german_names.save_dict()
	data["greek_islands"] = greek_islands.save_dict()
	data["iclandic_names"] = iclandic_names.save_dict()
	data["indian_names"] = indian_names.save_dict()
	data["irish_names"] = irish_names.save_dict()
	data["italian_names"] = italian_names.save_dict()
	data["japanese_names"] = japanese_names.save_dict()
	data["roman_names"] = roman_names.save_dict()
	data["latin_names"] = latin_names.save_dict()
	file.store_var(data)


func read(world_name: String) -> void:
	var file := FileAccess.open("user://worlds/%s/names.json" % (world_name), FileAccess.READ)
	if not file:
		russian_names = WordGenerator.new(WordGenerator.SourcePath.russian_names)
		satellites = WordGenerator.new(WordGenerator.SourcePath.satellites)
		scottish_names = WordGenerator.new(WordGenerator.SourcePath.scottish_names)
		spanish_names = WordGenerator.new(WordGenerator.SourcePath.spanish_names)
		swedish_names = WordGenerator.new(WordGenerator.SourcePath.swedish_names)
		swiss_names = WordGenerator.new(WordGenerator.SourcePath.swiss_names)
		capital_cities = WordGenerator.new(WordGenerator.SourcePath.capital_cities)
		chinese_names = WordGenerator.new(WordGenerator.SourcePath.chinese_names)
		constellations = WordGenerator.new(WordGenerator.SourcePath.constellations)
		cumbria_names = WordGenerator.new(WordGenerator.SourcePath.cumbria_names)
		dutch_names = WordGenerator.new(WordGenerator.SourcePath.dutch_names)
		english_names = WordGenerator.new(WordGenerator.SourcePath.english_names)
		french_names = WordGenerator.new(WordGenerator.SourcePath.french_names)
		german_names = WordGenerator.new(WordGenerator.SourcePath.german_names)
		greek_islands = WordGenerator.new(WordGenerator.SourcePath.greek_islands)
		iclandic_names = WordGenerator.new(WordGenerator.SourcePath.iclandic_names)
		indian_names = WordGenerator.new(WordGenerator.SourcePath.indian_names)
		irish_names = WordGenerator.new(WordGenerator.SourcePath.irish_names)
		italian_names = WordGenerator.new(WordGenerator.SourcePath.italian_names)
		japanese_names = WordGenerator.new(WordGenerator.SourcePath.japanese_names)
		roman_names = WordGenerator.new(WordGenerator.SourcePath.roman_names)
		latin_names = WordGenerator.new(WordGenerator.SourcePath.latin_names)
		return
		
	var data := file.get_var() as Dictionary
	russian_names.load_dict(data["russian_names"] as Dictionary)
	satellites.load_dict(data["satellites"] as Dictionary)
	scottish_names.load_dict(data["scottish_names"] as Dictionary)
	spanish_names.load_dict(data["spanish_names"] as Dictionary)
	swedish_names.load_dict(data["swedish_names"] as Dictionary)
	swiss_names.load_dict(data["swiss_names"] as Dictionary)
	capital_cities.load_dict(data["capital_cities"] as Dictionary)
	chinese_names.load_dict(data["chinese_names"] as Dictionary)
	constellations.load_dict(data["constellations"] as Dictionary)
	cumbria_names.load_dict(data["cumbria_names"] as Dictionary)
	dutch_names.load_dict(data["dutch_names"] as Dictionary)
	english_names.load_dict(data["english_names"] as Dictionary)
	french_names.load_dict(data["french_names"] as Dictionary)
	german_names.load_dict(data["german_names"] as Dictionary)
	greek_islands.load_dict(data["greek_islands"] as Dictionary)
	iclandic_names.load_dict(data["iclandic_names"] as Dictionary)
	indian_names.load_dict(data["indian_names"] as Dictionary)
	irish_names.load_dict(data["irish_names"] as Dictionary)
	italian_names.load_dict(data["italian_names"] as Dictionary)
	japanese_names.load_dict(data["japanese_names"] as Dictionary)
	roman_names.load_dict(data["roman_names"] as Dictionary)
	latin_names.load_dict(data["latin_names"] as Dictionary)
