class_name ControllerImageMap

const pc_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/key/shift.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/key/ctrl.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/mouse/left.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/mouse/right.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/key/space.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/key/r.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/key/e.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/key/q.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/key/z.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/key/alt.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/key/w.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/key/a.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/key/s.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/key/d.png[/img]",
}

const luna_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/luna/lt.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/luna/lb.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/luna/rt.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/luna/rb.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/luna/a.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/luna/x.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/luna/b.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/luna/y.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/luna/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/luna/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/luna/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/luna/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/luna/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/luna/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/luna/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/luna/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/luna/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/luna/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const ouya_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/ouya/l2.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/ouya/l1.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/ouya/r2.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/ouya/r1.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/ouya/o.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/ouya/u.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/ouya/a.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/ouya/y.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/ouya/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/ouya/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/ouya/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/ouya/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/xboxone/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/xboxone/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/ouya/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/ouya/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/ouya/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/ouya/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const ps3_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/ps3/l2.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/ps3/l1.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/ps3/r2.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/ps3/r1.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/ps3/cross.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/ps3/square.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/ps3/circle.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/ps3/triangle.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/ps3/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/ps3/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/ps3/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/ps3/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/ps3/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/ps3/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/ps3/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/ps3/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/ps3/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/ps3/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const ps4_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/ps4/l2.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/ps4/l1.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/ps4/r2.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/ps4/r1.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/ps4/cross.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/ps4/square.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/ps4/circle.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/ps4/triangle.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/ps4/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/ps4/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/ps4/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/ps4/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/ps4/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/ps4/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/ps4/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/ps4/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/ps4/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/ps4/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const ps5_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/ps5/l2.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/ps5/l1.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/ps5/r2.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/ps5/r1.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/ps5/cross.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/ps5/square.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/ps5/circle.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/ps5/triangle.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/ps5/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/ps5/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/ps5/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/ps5/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/ps5/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/ps5/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/ps5/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/ps5/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/ps5/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/ps5/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const stadia_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/stadia/lt.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/stadia/lb.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/stadia/rt.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/stadia/rb.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/stadia/a.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/stadia/x.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/stadia/b.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/stadia/y.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/stadia/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/stadia/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/stadia/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/stadia/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/xboxone/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/xboxone/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/stadia/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/stadia/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/stadia/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/stadia/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const steamdeck_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/steamdeck/l2.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/steamdeck/l1.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/steamdeck/r2.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/steamdeck/r1.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/steamdeck/a.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/steamdeck/x.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/steamdeck/b.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/steamdeck/y.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/steamdeck/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/steamdeck/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/steamdeck/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/steamdeck/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/steamdeck/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/steamdeck/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/steamdeck/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/steamdeck/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/steamdeck/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/steamdeck/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const switch_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/switch/zl.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/switch/l.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/switch/zr.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/switch/r.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/switch/a.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/switch/x.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/switch/b.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/switch/y.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/switch/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/switch/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/switch/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/switch/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/xboxone/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/xboxone/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/switch/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/switch/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/switch/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/switch/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const xbox360_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/xbox360/lt.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/xbox360/lb.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/xbox360/rt.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/xbox360/rb.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/xbox360/a.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/xbox360/x.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/xbox360/b.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/xbox360/y.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/xbox360/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/xbox360/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/xbox360/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/xbox360/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/xbox360/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/xbox360/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/xbox360/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/xbox360/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/xbox360/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/xbox360/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const xboxone_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/xboxone/lt.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/xboxone/lb.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/xboxone/rt.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/xboxone/rb.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/xboxone/a.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/xboxone/x.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/xboxone/b.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/xboxone/y.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/xboxone/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/xboxone/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/xboxone/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/xboxone/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/xboxone/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/xboxone/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/xboxone/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/xboxone/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/xboxone/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/xboxone/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}

const xboxseries_images = {
	"LT": "[img=%d]res://addons/controller_icons/assets/xboxseries/lt.png[/img]",
	"LB": "[img=%d]res://addons/controller_icons/assets/xboxseries/lb.png[/img]",
	"RT": "[img=%d]res://addons/controller_icons/assets/xboxseries/rt.png[/img]",
	"RB": "[img=%d]res://addons/controller_icons/assets/xboxseries/rb.png[/img]",
	"S": "[img=%d]res://addons/controller_icons/assets/xboxseries/a.png[/img]",
	"W": "[img=%d]res://addons/controller_icons/assets/xboxseries/x.png[/img]",
	"E": "[img=%d]res://addons/controller_icons/assets/xboxseries/b.png[/img]",
	"N": "[img=%d]res://addons/controller_icons/assets/xboxseries/y.png[/img]",
	"UP": "[img=%d]res://addons/controller_icons/assets/xboxseries/dpad_up.png[/img]",
	"DOWN": "[img=%d]res://addons/controller_icons/assets/xboxseries/dpad_down.png[/img]",
	"LEFT": "[img=%d]res://addons/controller_icons/assets/xboxseries/dpad_left.png[/img]",
	"RIGHT": "[img=%d]res://addons/controller_icons/assets/xboxseries/dpad_right.png[/img]",
	"L3": "[img=%d]res://addons/controller_icons/assets/xboxseries/l_stick_click.png[/img]",
	"R3": "[img=%d]res://addons/controller_icons/assets/xboxseries/r_stick_click.png[/img]",
	"move_forward": "[img=%d]res://addons/controller_icons/assets/xboxseries/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_up.png[/img]",
	"move_left": "[img=%d]res://addons/controller_icons/assets/xboxseries/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_left.png[/img]",
	"move_back": "[img=%d]res://addons/controller_icons/assets/xboxseries/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_down.png[/img]",
	"move_right": "[img=%d]res://addons/controller_icons/assets/xboxseries/l_stick.png[/img][img=%d]res://addons/controller_icons/assets/key/arrow_right.png[/img]",
}
