class_name World

enum Biome {
	WATER,
	GRASSLAND, TAIGA, FOREST, DESERT, JUNGLE, SAVANNAH, TUNDRA,
	OTHERWORLD, HFIL
}

enum Enemy {
	NONE, UNDEAD
}

enum Foliage {
	NONE,
	TREE_PYRAMID, TREE_ROUND, TREE_CHRISTMAS, TREE_SAFARI, TREE_BRANCHED
}

enum Building {
	NONE,
	FANTASY_VALLEY_SINGLE, FANTASY_VALLEY_DOUBLE
}
